### ISSUE TITLE
Please make a new release for use with composer

### ISSUE THREAD

**Issue by twogood** [there4/slim-test-helpers#16]
So we can use slim 2.6 as fixed by https://github.com/there4/slim-test-helpers/commit/a2b62feaba2e48fb288ced2133af495d7e039b40 and specify a version number for slim-test-helpers

**Comment by adbre** [comment]
v0.9.4 released.

> specify a version number for slim-test-helpers 
The version number was removed from composer.json in 96aec37, and as far as I know, we don't need a version number in composer.json, since composer/packagist will extract this from the version tag.
