### ISSUE TITLE
new release v2.1.2 ?

### ISSUE THREAD

**Issue by sbernard31** [there4/slim-test-helpers#38]
Hi,
   Any chance to get a new release with the last fixes : 855875589f20d05d9844d381484cc1664ba5a20e
Thx :)

**Comment by craig-davis** [comment]
hi @sbernard31, I'm tied up this weekend. I don't want to block you on anything. I've added you as a contributor, and I think you can make a new release for us all. Go for it!

**Comment by sbernard31** [comment]
Thx, I made the release and tested it, it seems ok. I close this issue. :)
